### ISSUE TITLE
New PSI repo for StreamDevice

### ISSUE THREAD

**Issue by anjohnson** [epics-modules/stream#5]
Keenan pointed out that Dirk now publishes StreamDevice in a github repo at https://github.com/paulscherrerinstitute/StreamDevice

There is still no configure directory in Dirk's version though; someone should convert this repo into a wrapper that pulls in Dirk's repo as a git submodule. This should work properly since his top-level Makefile sets `TOP=..` so it expects to be embedded in a subdirectory anyway. I can offer advice on git submodules if help is needed.

You could then consider turning off github issues for this repo and making sure that Dirk's repo is clearly referenced in the README.md file.

**Comment by keenanlang** [comment]
If we switch over to a submodule, is there an easy way to alter the build files to force the EPICS build system to use Stream's Makefile file instead of the GNUmakefile file that's for PSI's build system?

Base's RULES file sets make's -f flag to only search for makefiles called Makefile, but RULES_DIRS doesn't, so GNUmakefile takes precedent.

**Comment by anjohnson** [comment]
Yes, since you control the contents of the configure directory, and all IOC Makefiles include files from there rather than directly from Base/configure. One way would be to copy RULES_DIRS from Base (instead of including it like the standard IOC/configure/RULES_DIRS file does) and modify the line that calls `$(MAKE)` to add the flag `-f Makefile`. There may be a less drastic method but it's not springing to mind immediately.
